apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: arcade.azurecr.io/gateway-svc:{{DOCKER_IMAGE_VERSION}}
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: ClientApp
            value: https://app.rayinaw.one
          - name: IdentityServiceUrl
            value: https://identity.rayinaw.one
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80
