apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: CONTAINER_REGISTRY/web-app:{{DOCKER_IMAGE_VERSION}}
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: NEXTAUTH_SECRET
          - name: NEXTAUTH_URL
            value: https://app.rayinaw.one
          - name: API_URL
            value: http://gateway-clusterip
          - name: ID_URL
            value: https://identity.rayinaw.one
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 3000


