apiVersion : apps/v1
kind: Deployment
metadata:
  name: demoproject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoproject
  template:
    metadata:
      labels:
        app: demoproject 
    spec:
      containers:
        - name: demoproject 
          image: arcade.azurecr.io/demoproject
          ports:
          - containerPort: 3000